export type Artwork = {
  src: string;
  /** Optional lightweight source used only by the physical-scale wall. */
  scaleSrc?: string;
  title: string;
  width: number | null;
  height: number | null;
  medium: string | null;
  year: string;
  /** Use `about` to feature an image on the About page instead of the gallery. */
  placement?: "gallery" | "about";
  /** Optional display-only scale: 0.8 renders the image at 80% width. */
  displayScale?: number;
  /** Set to false for detail or context photos that are not standalone works. */
  scaleView?: boolean;
  /** Optional one-based page override in the to-scale gallery. */
  scalePage?: number;
};

/**
 * The gallery's source of truth.
 *
 * - `width` and `height` are the artwork's physical dimensions in inches.
 * - Comment out an entire object to hide that work from the gallery.
 * - The gallery sorts years newest-first; this order breaks ties within a year.
 * - `displayScale` changes only the on-screen image size, never its dimensions.
 */
export const artworks: Artwork[] = [
  {
    src: "/artwork/roar.jpg",
    scaleSrc: "/artwork/scale/roar.webp",
    title: "Roar",
    width: 8,
    height: 10,
    medium: "Oil on Canvas",
    year: "2023",
  },
  {
    src: "/artwork/cozy.jpg",
    scaleSrc: "/artwork/scale/cozy.webp",
    title: "Cozy",
    width: 7,
    height: 5,
    medium: "Sketchbook",
    year: "2022",
  },
  {
    src: "/artwork/unravel.jpg",
    scaleSrc: "/artwork/scale/unravel.webp",
    title: "Unravel",
    width: 24,
    height: 36,
    medium: "Oil on Canvas",
    year: "2023",
    scalePage: 1,
  },
  {
    src: "/artwork/blame.jpg",
    scaleSrc: "/artwork/scale/blame.webp",
    title: "Blame",
    width: 24,
    height: 24,
    medium: "Oil on Canvas",
    year: "2023",
    scalePage: 1,
  },
  {
    src: "/artwork/rising.jpg",
    scaleSrc: "/artwork/scale/rising.webp",
    title: "Rising",
    width: 12,
    height: 24,
    medium: "Oil on Board",
    year: "2024",
    scalePage: 2,
  },
  //{
  //  src: "/artwork/landscape.jpg",
  //  title: "Landscape",
 //   width: 12,
 //   height: 12,
 //   medium: "Oil on Canvas",
  //  year: "2022",
  //},
  {
    src: "/artwork/boots.jpg",
    scaleSrc: "/artwork/scale/boots.webp",
    title: "Boots",
    width: 8,
    height: 10,
    medium: "Acrylic on Canvas",
    year: "2021",
  },
  {
    src: "/artwork/pick.jpg",
    scaleSrc: "/artwork/scale/pick.webp",
    title: "Pick",
    width: 9,
    height: 12,
    medium: "Graphite on Paper",
    year: "2020",
  },
  {
    src: "/artwork/gotcha.jpg",
    scaleSrc: "/artwork/scale/gotcha.webp",
    title: "Gotcha",
    width: 12,
    height: 9,
    medium: "Graphite on Paper",
    year: "2020",
  },
  {
    src: "/artwork/reflection.jpg",
    scaleSrc: "/artwork/scale/reflection.webp",
    title: "Reflection",
    width: 10,
    height: 10,
    medium: "Oil on Linen Paper",
    year: "2021",
  },
  {
    src: "/artwork/still-life-egg.jpg",
    scaleSrc: "/artwork/scale/still-life-egg.webp",
    title: "Still Life: Egg",
    width: 12,
    height: 9,
    medium: "Graphite on Paper",
    year: "2018",
  },
  {
    src: "/artwork/anubis-dream.jpg",
    scaleSrc: "/artwork/scale/anubis-dream.webp",
    title: "Anubis Dream",
    width: 16,
    height: 24,
    medium: "Oil on Canvas",
    year: "2022",
    scalePage: 1,
  },
  {
    src: "/artwork/studio-pic-stanford.jpg",
    title: "Stanford studio",
    width: null,
    height: null,
    medium: null,
    year: "2026",
  },
  {
    src: "/artwork/cows.jpg",
    scaleSrc: "/artwork/scale/cows.webp",
    title: "Cows",
    width: 12,
    height: 12,
    medium: "Acrylic on Canvas",
    year: "2020",
  },
  {
    src: "/artwork/DONTLOOK-sketch.jpg",
    title: "DONTLOOK — Sketch",
    width: 5,
    height: 7,
    medium: "Oil on Paper",
    year: "2026",
    scaleView: false,
  },
  {
    src: "/artwork/wash.jpg",
    scaleSrc: "/artwork/scale/wash.webp",
    title: "Wash",
    width: 12,
    height: 12,
    medium: "Oil on Canvas",
    year: "2022",
  },
  {
    src: "/artwork/DONTLOOKATME.jpg",
    scaleSrc: "/artwork/scale/DONTLOOKATME.webp",
    title: "DONTLOOK (weird fish)",
    width: 36,
    height: 48,
    medium: "Oil on Canvas",
    year: "2026",
  },
  {
    src: "/artwork/studio-pic.jpg",
    title: "home studio (basement closet)",
    width: null,
    height: null,
    medium: null,
    year: "2024",
    placement: "about",
  },
  {
    src: "/artwork/heritage.jpg",
    scaleSrc: "/artwork/scale/heritage.webp",
    title: "Heritage",
    width: 9,
    height: 12,
    medium: "Oil on Linen Paper",
    year: "2024",
  },
  {
    src: "/artwork/tiedup.jpg",
    scaleSrc: "/artwork/scale/tiedup.webp",
    title: "Tied Up",
    width: 48,
    height: 96,
    medium: "Acrylic on Composite Board",
    year: "2024",
    scalePage: 2,
  },
  {
    src: "/artwork/bastion.jpg",
    scaleSrc: "/artwork/scale/bastion.webp",
    title: "Bastion",
    width: 36,
    height: 48,
    medium: "Oil on Canvas",
    year: "2024",
    scalePage: 2,
  },
  {
    src: "/artwork/mirror:rorrim.jpg",
    scaleSrc: "/artwork/scale/mirror:rorrim.webp",
    title: "mirror:rorrim",
    width: 10,
    height: 10,
    medium: "Graphite on Paper",
    year: "2022",
  },
  {
    src: "/artwork/fresh.jpg",
    scaleSrc: "/artwork/scale/fresh.webp",
    title: "Fresh",
    width: 24,
    height: 36,
    medium: "Oil on Canvas",
    year: "2024",
  },
  {
    src: "/artwork/fresh-closeup.jpg",
    title: "Fresh — Close-up",
    width: 16,
    height: 16,
    medium: "Oil on Canvas",
    year: "2024",
    scaleView: false,
  },
  {
    src: "/artwork/handsoff.jpg",
    scaleSrc: "/artwork/scale/handsoff.webp",
    title: "Hands Off",
    width: 10,
    height: 10,
    medium: "Oil on Linen Paper",
    year: "2023",
    scalePage: 1,
  },
  {
    src: "/artwork/inside-out.jpg",
    scaleSrc: "/artwork/scale/inside-out.webp",
    title: "Inside Out",
    width: 10,
    height: 10,
    medium: "Graphite on Paper",
    year: "2022",
  },
  {
    src: "/artwork/still-life.jpg",
    scaleSrc: "/artwork/scale/still-life.webp",
    title: "Still Life",
    width: 12,
    height: 9,
    medium: "Acrylic on Paper",
    year: "2018",
  },
  {
    src: "/artwork/oasis.jpg",
    scaleSrc: "/artwork/scale/oasis.webp",
    title: "Oasis",
    width: 36,
    height: 48,
    medium: "Oil on Canvas",
    year: "2021",
    scalePage: 1,
  },
  {
    src: "/artwork/the-walls-we-build.jpg",
    scaleSrc: "/artwork/scale/the-walls-we-build.webp",
    title: "The Walls We Build",
    width: 48,
    height: 48,
    medium: "Oil on Canvas",
    year: "2022",
    scalePage: 2,
  },
];
